In [1]:
import pandas as pd
import numpy as np

filename = "NCANDA_S01010_run-01.feat__filtered_func.nii.gz.1D"
df = pd.read_csv(filename, sep='\t', header=None) 

In [43]:
df.shape

(269, 529)

In [3]:
df.head()

0            1            2            3            4           5    \
0  NaN  1682.870932  1610.899658  1569.892853  1519.308350  855.376494   
1  NaN  1697.569767  1637.081421  1582.578522  1543.433838  862.772507   
2  NaN  1691.078225  1620.775879  1609.190918  1556.537720  860.337983   
3  NaN  1702.101509  1630.589355  1607.464267  1562.899658  849.476986   
4  NaN  1716.043358  1638.569092  1635.874869  1576.715088  848.912162   

          6           7           8           9    ...          519  \
0  789.789673  267.811067  236.602737  129.980806  ...  4082.771162   
1  810.230957  279.417848  257.662537  121.348412  ...  4063.495932   
2  805.921875  281.801626  255.386353  125.857288  ...  4072.053807   
3  791.579468  281.374051  257.909973  128.275750  ...  4078.613464   
4  797.978149  277.272182  250.664337  128.967759  ...  4082.159589   

           520          521          522          523          524  \
0  4079.775391  3898.254940  3893.541992  3603.489933  3595.153320   
1  4060.885254  3892.599239  3890.902588  3642.685844  3637.665039   
2  4067.200195  3890.321200  3894.753662  3623.019971  3617.502197   
3  4074.968750  3896.750875  3897.742188  3641.734855  3631.630859   
4  4085.481445  3907.285632  3904.280273  3652.275745  3646.895508   

           525          526          527          528  
0  3403.906424  3408.472656  3647.815922  3650.031006  
1  3400.070561  3403.722168  3645.860400  3645.820312  
2  3410.859397  3410.782471  3632.484807  3638.976074  
3  3411.606707  3411.334717  3641.445849  3640.393066  
4  3411.781533  3411.574707  3647.481306  3655.821533  

[5 rows x 529 columns]

In [8]:
df = df.iloc[:,1::]

In [9]:
df.head()

1            2            3            4           5           6    \
0  1682.870932  1610.899658  1569.892853  1519.308350  855.376494  789.789673   
1  1697.569767  1637.081421  1582.578522  1543.433838  862.772507  810.230957   
2  1691.078225  1620.775879  1609.190918  1556.537720  860.337983  805.921875   
3  1702.101509  1630.589355  1607.464267  1562.899658  849.476986  791.579468   
4  1716.043358  1638.569092  1635.874869  1576.715088  848.912162  797.978149   

          7           8           9           10   ...          519  \
0  267.811067  236.602737  129.980806  119.739105  ...  4082.771162   
1  279.417848  257.662537  121.348412  108.592239  ...  4063.495932   
2  281.801626  255.386353  125.857288  119.131706  ...  4072.053807   
3  281.374051  257.909973  128.275750  116.361565  ...  4078.613464   
4  277.272182  250.664337  128.967759  119.113174  ...  4082.159589   

           520          521          522          523          524  \
0  4079.775391  3898.254940  3893.541992  3603.489933  3595.153320   
1  4060.885254  3892.599239  3890.902588  3642.685844  3637.665039   
2  4067.200195  3890.321200  3894.753662  3623.019971  3617.502197   
3  4074.968750  3896.750875  3897.742188  3641.734855  3631.630859   
4  4085.481445  3907.285632  3904.280273  3652.275745  3646.895508   

           525          526          527          528  
0  3403.906424  3408.472656  3647.815922  3650.031006  
1  3400.070561  3403.722168  3645.860400  3645.820312  
2  3410.859397  3410.782471  3632.484807  3638.976074  
3  3411.606707  3411.334717  3641.445849  3640.393066  
4  3411.781533  3411.574707  3647.481306  3655.821533  

[5 rows x 528 columns]

In [3]:
df.shape

(269, 528)

In [2]:
mean = df.iloc[:,1::2].to_numpy().astype(np.float32)
mean.shape

(269, 264)

In [5]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(mean)
X_scaled = scaler.transform(mean)

In [7]:
X_scaled.shape

(269, 264)

In [8]:
X_scaled

array([[ 0.54791445, -2.205332  ,  1.4644797 , ..., -2.0584586 ,
        -1.1008956 , -0.12641895],
       [ 1.3996116 , -1.7569087 ,  1.9576976 , ...,  0.75588423,
        -1.1954408 , -0.22453724],
       [ 1.0234694 , -0.81619096,  1.7953485 , ..., -0.6561604 ,
        -0.92952657, -0.895637  ],
       ...,
       [ 0.28434125,  0.44667464, -0.41404003, ...,  0.8119271 ,
         1.3573074 ,  0.15052943],
       [ 0.9406572 ,  1.5317001 , -0.86084515, ...,  0.01854492,
         1.526486  ,  0.29849082],
       [-1.4059889 , -0.602782  , -1.4020388 , ...,  1.6850699 ,
         1.6912841 ,  0.6256008 ]], dtype=float32)

In [12]:
import torch
torch.randn(264)

tensor([-0.3611,  0.4918, -0.5540,  0.3499, -0.9785,  0.7034,  2.9509,  1.9345,
        -1.6317, -0.0879,  0.0508, -1.3766,  1.3198,  0.6977, -0.3382, -0.6307,
        -0.0203, -0.6318, -1.6345, -0.9259,  0.7250, -1.0283, -0.0036, -0.8241,
         0.0083, -1.1871,  1.5538, -0.6260,  0.6042,  1.5055,  0.0880,  0.1972,
        -0.2271,  1.4975,  0.8703, -1.4955, -0.3549, -1.5776,  0.1272, -1.0559,
        -0.6383,  1.0138, -0.1557,  1.0369, -0.3808,  0.3126, -1.9406,  0.9570,
        -0.1706,  1.3011, -1.6338,  1.3933,  0.1429, -0.6198, -0.0911, -0.1486,
         0.1556,  2.3167, -1.4948, -2.2918,  2.1877, -1.3840,  0.5380, -0.7230,
        -0.1120, -0.7997,  1.6869,  0.0984,  0.3853, -1.1027, -0.6760, -0.0278,
         1.0903,  0.8943,  0.9145,  0.0092,  1.9206,  1.3139,  0.5482,  0.6147,
        -1.1204,  0.7206, -0.3276,  1.6444, -0.1027,  1.6611,  1.1672, -1.1570,
         2.8939, -2.0304, -1.2154, -0.5305,  0.7983,  0.4083, -0.2376, -1.0552,
        -0.4090, -0.3477,  0.7967, -0.39

In [17]:
filename = "NCANDA_S01010_run-01.feat__filtered_func.nii.gz.1D"
df = pd.read_csv(filename, sep='\t', header=None) 
df = df.iloc[:,1::]

##split the mean(odd col nums) and median(even col nums) series
mean = df.iloc[:,1::2].to_numpy().astype(np.float32)
#median = df.iloc[:,0::2].to_numpy().astype(np.float32)

scaler = preprocessing.StandardScaler().fit(mean)
scaled = scaler.transform(mean)
obs = torch.from_numpy(scaled)
obs

tensor([[ 0.4166, -1.7272,  1.3380,  ..., -2.2370, -0.9620, -0.4122],
        [ 1.6704, -0.7088,  2.5102,  ...,  0.7381, -1.0963, -0.6001],
        [ 0.8896, -0.1556,  2.2631,  ..., -0.6729, -0.8967, -0.9055],
        ...,
        [-0.4868, -0.1659, -0.2339,  ...,  0.6928,  1.2303,  0.5217],
        [-0.0500,  1.5087,  0.0819,  ...,  0.0724,  1.3501,  0.3616],
        [-1.5403, -1.0603, -1.0873,  ...,  1.5272,  1.9244,  0.7664]])

In [30]:
np.all(scaled)

True

In [21]:
max(obs[1])

tensor(2.9042)

In [23]:
min(obs[0])

tensor(-2.8944)

In [14]:
obs = np.reshape(obs, (269,1,264))
obs

tensor([[[ 0.4166, -1.7272,  1.3380,  ..., -2.2370, -0.9620, -0.4122]],

        [[ 1.6704, -0.7088,  2.5102,  ...,  0.7381, -1.0963, -0.6001]],

        [[ 0.8896, -0.1556,  2.2631,  ..., -0.6729, -0.8967, -0.9055]],

        ...,

        [[-0.4868, -0.1659, -0.2339,  ...,  0.6928,  1.2303,  0.5217]],

        [[-0.0500,  1.5087,  0.0819,  ...,  0.0724,  1.3501,  0.3616]],

        [[-1.5403, -1.0603, -1.0873,  ...,  1.5272,  1.9244,  0.7664]]])

In [ ]:
mi

In [15]:
obs.shape

torch.Size([269, 1, 264])