In [36]:
import numpy as np
import copy

In [37]:
A_dist = np.load("A_dist_result.npy")
C_dist = np.load("C_dist_result.npy")

In [38]:
A_dist.round(2)

array([ 6.79, 10.28,  4.79,  4.74,  1.92, 36.24,  2.24], dtype=float32)

In [41]:
C_dist.round(2)

array([0.53, 1.4 , 4.57, 0.  , 3.39, 0.63, 1.14])

In [34]:
A_esti = np.load("A_esti_result.npy")
C_esti = np.load("C_esti_result.npy")

In [25]:
A_esti

array([[[[-0.5696813 ,  0.01359357,  0.4755609 ],
         [-0.23195508, -0.00732104,  0.3094718 ],
         [-0.9143873 , -0.9548852 , -0.5025163 ]]],


       [[[-0.79425293, -0.18338038, -1.6057466 ],
         [-0.21645515,  0.48148865,  0.02663619],
         [ 0.8684975 , -0.25905544, -0.2962885 ]]],


       [[[ 0.435527  ,  0.6169542 ,  0.4950063 ],
         [-0.47222316, -0.1798818 , -0.17089485],
         [ 1.3347944 ,  0.00247648, -0.4244518 ]]],


       [[[ 0.10527217,  0.42036688,  0.15610144],
         [-0.6365484 ,  0.5623134 ,  0.4399983 ],
         [ 1.0894613 , -0.29296038, -0.05248955]]],


       [[[ 0.6895373 ,  0.7993525 ,  0.52918684],
         [-1.3930272 , -0.09153878,  0.12867054],
         [ 0.85805345, -0.48354468, -0.5126971 ]]],


       [[[-0.06038045, -0.38808718,  0.93264586],
         [ 0.24041946,  0.02262599,  0.10166792],
         [ 0.7535015 ,  0.6492031 ,  0.07277396]]],


       [[[ 0.20215295,  0.7141304 , -0.790326  ],
         [-0.2795924 , -0.

In [35]:
C_esti

array([[[-9.91675037e+01,  1.71432640e+02,  1.18250828e+03],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 1.15356761e+02,  5.31467798e+02,  1.79617616e+01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 1.09800670e+02, -1.81716402e+02, -2.65410743e+02],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 3.24083813e+03, -1.32598503e+03,  3.27014133e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[-1.15733249e+02,  1.50575664e+03, -1.25850310e+01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 2.14982538e+03, -2.82337247e+00,  1.55010399e+01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 7.58593766e+01,  1.54318928e+02, -1.69105241e+01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[-9.89998236e+01, -7.30256758e+01, -3.46470942e+01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [

In [19]:
A_dist

array([  3.268592 ,  70.82761  ,   3.0293539,   4.59608  ,  14.4142885,
         2.214546 ,   4.2438726,   2.094254 , 189.73857  ,   2.6700838],
      dtype=float32)

In [17]:
C_dist

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
C_simu

array([[ 4.68276325e+09, -3.07792430e+09,  5.14261505e+10],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [8]:
A_simu

array([[-0.10245468,  4.4950805 , -0.6321727 ],
       [-0.08151823,  0.4734365 , -0.09669829],
       [ 0.34073275,  1.8171802 , -2.7721198 ]], dtype=float32)

In [3]:
#load data
A_simu = np.load("A_result4.npy")
C_simu = np.load("C_result4.npy")

#normalize data
A_norm = copy.deepcopy(A_simu)
C_norm = copy.deepcopy(C_simu)
for i in range(len(A_simu)):
    A_norm[i] = normalize(A_simu[i])
    C_norm[i] = normalize(C_simu[i])

A_gt = np.array([[-0.6, 0.7, -0.8], [-0.2, 0.3, 1.1], [0.2, -0.5, -0.5]])
C_gt = np.array([[-0.4, 0, 0], [0, 0, 0]])
A_gt_norm = normalize(A_gt)
C_gt_norm = normalize(C_gt)

ValueError: Expected 2D array, got 1D array instead:
array=[ 0.30249655 -0.08546965  1.2313422 ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [17]:
A_gt

array([[-0.6,  0.7, -0.8],
       [-0.2,  0.3,  1.1],
       [ 0.2, -0.5, -0.5]])

In [19]:
A_simu[10].round(2)

array([[-0.6 ,  1.  , -0.32],
       [-0.09, -0.24, -0.09],
       [ 0.21, -0.39,  0.03]], dtype=float32)

In [18]:
C_simu[10]

array([[-0.15322925, -0.04069975, -0.50912608],
       [ 0.        ,  0.        ,  0.        ]])

In [13]:
A_norm[0]

array([[-0.19658057,  0.05102392,  0.9791591 ],
       [-0.15293168,  0.069586  ,  0.98578376],
       [-0.1851687 , -0.01829852, -0.9825364 ]], dtype=float32)

In [14]:
A_norm[29]

array([[-0.14770466, -0.02202011,  0.9887864 ],
       [-0.03553669,  0.06669316,  0.9971405 ],
       [ 0.05078509, -0.24902986, -0.9671634 ]], dtype=float32)

In [21]:
A_norm[10].round(2)

array([[-0.5 ,  0.83, -0.27],
       [-0.34, -0.87, -0.34],
       [ 0.47, -0.88,  0.07]], dtype=float32)

In [20]:
A_gt_norm.round(2)

array([[-0.49,  0.57, -0.66],
       [-0.17,  0.26,  0.95],
       [ 0.27, -0.68, -0.68]])

In [ ]:
#generate data graph
A_dist = []
G2 = nx.from_numpy_matrix(A_gt_norm)
for data in A_norm:
    G1 = nx.from_numpy_matrix(data)

    #then calculate adjancent matrix
    A1, A2 = [nx.adjacency_matrix(G) for G in [G1,G2]]
    
    #calculate distance matrix
    norm_dist = np.linalg.norm(A1 - A2)
    spec_dist = nc.lambda_dist(A1, A2)
    edit_dist = nc.edit_distance(A1, A2)
    #netsmile_dist = nc.netsimile(A1, A2)

    result = [norm_dist, spec_dist, edit_dist]
    A_dist.append(result)

In [ ]:
np.save("A_dist.npy", A_dist)

In [ ]:
C_dist = []
G4 = nx.from_numpy_matrix(C_gt_norm)
for data2 in C_norm:
    G3 = nx.from_numpy_matrix(data2)

    #then calculate adjancent matrix
    A3, A4 = [nx.adjacency_matrix(G) for G in [G3, G4]]
    
    norm_dist2 = np.linalg.norm(A3 - A4)
    spec_dist2 = nc.lambda_dist(A3, A4)
    edit_dist2 = nc.edit_distance(A3, A4)
    netsmile_dist2 = nc.netsimile(A3, A4)

    result2 = [norm_dist2, spec_dist2, edit_dist2, netsmile_dist2]
    C_dist.append(result2)


np.save("C_dist.npy", C_dist)

In [10]:
AC_dist = np.load("AC_dist.npy", allow_pickle= True)

In [19]:
C_gt = np.array([[-0.4, 0, 0], [0, 0, 0]])

In [14]:
C_result = np.load("C_result.npy")

In [18]:
C_result[3]/C_result[3][0,0]

array([[ 1.        ,  0.05374411, -0.07694847],
       [-0.        , -0.        , -0.        ]])

In [20]:
C_gt/-0.4

array([[ 1., -0., -0.],
       [-0., -0., -0.]])

In [22]:
A_result = np.load("A_result.npy")

In [27]:
A_result[14]/A_result[14][0,0]

array([[ 1.        , -0.6179883 ,  0.5071678 ],
       [ 0.4263735 ,  0.1005426 ,  0.09398197],
       [-0.28833583,  0.03708019, -0.00269091]], dtype=float32)

In [24]:
A_result[12]/A_result[12][0,0]

array([[ 1.        , -0.9066843 ,  0.61314434],
       [ 1.0320673 ,  0.3082426 , -0.3347908 ],
       [-0.46646282,  0.60770065, -0.34581706]], dtype=float32)

In [25]:
A_gt = np.array([[1.0, 0.4, -0.2], [-0.5, 0.3, 1.0], [0.2, 1, -0.5]])
A_gt/A_gt[0,0]

array([[ 1. ,  0.4, -0.2],
       [-0.5,  0.3,  1. ],
       [ 0.2,  1. , -0.5]])

In [11]:
AC_dist[3]

array([3.68109379, 0.09385892])

In [5]:
for i in AC_dist:
    print(i[0])
    print("-----")
    print(i[1])
    print("=========")

11.026989656387862
-----
0.14499600650845135
11.68027278185689
-----
5.428112398193225
2.9425771530012472
-----
0.9946839626183996
3.6810937926995964
-----
0.09385891590498491
2.459412437787328
-----
22.13200726313492
5.920800572759732
-----
0.06564218541208666
2.3522424670132915
-----
2.581519759130896
80.80960245720497
-----
0.0773469660532532
81.70910128442029
-----
30.983326476821865
7.828000439898012
-----
2.326044412769087
2.548358982012859
-----
3.3332427122462964
11.764836183571926
-----
7.568096015515397
2.330752501376978
-----
2.3403224579246196
4.621665072547697
-----
6.131448740902832
2.5303023490327994
-----
0.414567730975685
2.786991540905349
-----
0.5262169091971931
4.055419267864342
-----
0.5087016099168407
12.19794087749299
-----
6.670048184865025
105.58438015139706
-----
1.960065688387106
2.7121355623714622
-----
6.583089484205761
2.6072361219279987
-----
0.42746660154691796
98.64702410113853
-----
0.2852463573824924
2.6916998020766107
-----
1.1446415609696785
11.0940